### ISSUE TITLE
DEAL

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#11]
Is there a possibility to indicate a reference to DEAL or similar?

**Comment by aw-bib** [comment]
The initially proposed format does _not yet_ handle transformative agreements like DEAL, but assumes article based fees only. This is a restriction made to enable as early as possible involvement with the community.

**Comment by vossviola** [comment]
Is this not the information meant for the field `part_of_contract`?

**Comment by aw-bib** [comment]
> Is this not the information meant for the field part_of_contract?

In fact it is, but wrt my comment above, right now we focus on articles with a dedicated bill. So the whole chain on _what happens if `part_of_contract` is not empty_ is still missing for the time being.
