### ISSUE TITLE
What is the source of `date_paid`?

### ISSUE THREAD

**Issue by aw-bib** [opencost-de/opencost#17]
Does it refer to the date of the invoice?

reportedBy: @pampel

**Comment by vossviola** [comment]
I would think that this is the date the payment has actually been done, i.e. e.g. the date of the local SAP booking?

**Comment by aw-bib** [comment]
Actually, at DESY at least we stick with the date of the invoice. This also has some pragmatic advantages. Especially if we have to convert currencies, we need to find the actual booking in the first place and then the date of the invoice comes in very handy.

OTOH I strongly hope that the date of the actual payment and the date of the invoice don't differ too much.
