### ISSUE TITLE
Why is "type" field not multiple?

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#19]
As we need to be able to divide the costs into APC, page charges et al. Then of course only the first field should be required (the others optional) - or in combination with "amount_paid" (also only once required).

ReportBy: email

**Comment by cbroschinski** [comment]
`type` may in fact occur more than once. In our currenct XML implementation `type` (together with `currency`) is a mandatory attribute to the  `amount_paid` element, which itself can have mutiple occurences (Here's an [example](https://github.com/opencost-de/opencost/blob/main/doc/examples/gold_oa.xml#L7-L8)). This was somewhat misleading in previous versions of the schema description, we have now tried to make it [more clear](https://github.com/opencost-de/opencost/tree/main/doc#item).
