### ISSUE TITLE
"Voucher" element

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#35]
Would it be possible to include an explicit null value (none), so that articles, conference contributions, etc., for which nothing was paid, can also be deposited (incl. justification)? For example by a "voucher" element or similar.

ReportBy: online discussion 2/3/23

**Comment by aw-bib** [comment]
At JOIN² we handle vouchers along with the status of the payment, that is we set `Voucher` as status and costtype would be `APC`.

As an example: say we get a voucher from some Open Access publisher. In principle we would have to pay some amount of APCs. Hence we would set `voucher` price to 0 and expose it like:

```xml
      <opencost:amounts_paid>
        <opencost:amount_paid currency="EUR" type="apc">0</opencost:amount_paid>
        <opencost:amount_paid currency="EUR" type="vat">0</opencost:amount_paid>
      </opencost:amounts_paid>
```

I wonder if this is _good enough_ or causes some headache further down the road.

**Comment by bschweighofer** [comment]
We have updated our documentation accordingly and included the question in our FAQs.
