### ISSUE TITLE
Splitted invoices among several institutions

### ISSUE THREAD

**Issue by zuphilip** [opencost-de/opencost#40]
An invoice can be splitted among several institutions. We have this cases in practices especially for expensive OA books but also if the BW consortial pays an amount and an individual library the remaining price. One can currently have multiple `opencost:institutions/opencost:institution` nodes and therefore try someting like this:
```xml
<opencost:institutions>
    <opencost:institution type="full name">University A</opencost:institution>
    <opencost:institution type="ror">999xxx000</opencost:institution>
    <opencost:institution type="full name">University B</opencost:institution>
</opencost:institutions>
```
However, it is then not clear anymore which lines belong together, i.e. indicated the same entity.

One possibility could be to switch all the ids to become attributes instead, e.g.
```xml
<opencost:institutions>
    <opencost:institution ror="999xxx000">University A</opencost:institution>
    <opencost:institution>University B</opencost:institution>
</opencost:institutions>
```

**Comment by aw-bib** [comment]
I'll move your comment to the other issue we have already so it does not get lost.

isDupeTo: #2
