### ISSUE TITLE
Renaming of the `publisher` field 

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#43]
The field name `publisher` could be misleading, from SAP's point of view it would rather be called creditor. In addition, it is not entirely clear what exactly is to be recorded here (e.g., in the case of an MPDL invoice, is it MPDL or Springer or Wiley?).

**Comment by aw-bib** [comment]
What is our main intention here? I think it is on the lines of `who gets the money`, right?

The naming `publisher` AFAIS mainly results from _I published a paper with X, so x got the money, and X is the publisher_. This indeed falls short in cases where costs are not associated with the publisher but with some other party. E.g. in view of #49 the proposed cost types like `bank transfer`, `credit card` and even more so for `editing`. Usually we would not pay fees to the publisher.

Additionally, the `publisher` of the article in question is part of the bibliographic description (given in _some way_).

So indeed we should have some better name her.
