### ISSUE TITLE
Add `<data`>-element

### ISSUE THREAD

**Issue by aw-bib** [opencost-de/opencost#55]
While openCost schemas are envisioned to be used in OAI-harvesting, we can add additional flexiblity if we  _per see_ allow the submission of a batch of records in one openCost structure. This requires an additional "bracket" around the individual `openCost` blocks.

For item-based charges we [recently added](https://github.com/opencost-de/opencost/commit/66ccf22c290a6948b27deb349bce2c856ec4ae2d) an additional `<opencost:data/>` element. This should also be added to the `contracts` schmema.

isRelatedTo: https://github.com/opencost-de/opencost/commit/66ccf22c290a6948b27deb349bce2c856ec4ae2d

**Comment by cbroschinski** [comment]
This is [already done](https://github.com/opencost-de/opencost/blob/main/doc/opencost.xsd#L8-L21). `<data>` is designed  to wrap both `<contract>` and `<publication>` elements (also in combination).
