### ISSUE TITLE
Amount_invoice in net and gross

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#7]
Can the "amount_invoice" be indicated in net and in gross; (possibly with reference to the corresponding amount of VAT)?

**Comment by aw-bib** [comment]
This seems to be unclear in our textual documentation. The XML / XSD imageins net/gross to be modeled like:

```xml
     <opencost:amounts_paid>
        <opencost:amount_paid currency="EUR" type="apc">1500.00</opencost:amount_paid>
        <opencost:amount_paid currency="EUR" type="vat">14.25</opencost:amount_paid>
      </opencost:amounts_paid>
````

IOW the VAT is a fee `type`, hence it follows that the amount of the fee as such (here: apc) should be net.

**Comment by patrickda** [comment]
An other option would be to add the VAT in % makes it easier to spot differences.

**Comment by vossviola** [comment]
The net/gross distinction and the type "vat" for `amount_paid` should definitely be mentioned in the textual documentation.

**Comment by bschweighofer** [comment]
>An other option would be to add the VAT in % makes it easier to spot differences.

We decided to use currency as the computer can do the calculation. We only define an exchange format.
