### ISSUE TITLE
"Currency"

### ISSUE THREAD

**Issue by bschweighofer** [opencost-de/opencost#8]
Shouldn't "currency" appear twice? Once for "amount_invoice" and second for "amount_paid"? Also, wouldn't "currency" be non-required, if "amount_invoice" is also not required?

ReportBy: email

**Comment by aw-bib** [comment]
This should be clearified in our written documentation.

The XML / XSD specifies the currency as an attribute to `amount_invoice`:

```xml
 <opencost:amount_invoice currency="GBP">1234.56</opencost:amount_invoice>
```

(here: `GBP`). Furthermore the individual items of said invoice again feature `currency` attributes like

```xml
     <opencost:amounts_paid>
        <opencost:amount_paid currency="EUR" type="apc">1500.00</opencost:amount_paid>
        <opencost:amount_paid currency="EUR" type="vat">14.25</opencost:amount_paid>
      </opencost:amounts_paid>
```

**Comment by cbroschinski** [comment]
`currency` is indeed a mandatory attribute for all `amount_invoice` and `amount_paid` elements. The XML Schema already enforces this, the [description](https://github.com/opencost-de/opencost/tree/main/doc#item) has been updated to make this more clear.
